type: fields
fields:
  headline:
    type: headline
    label: LLMs Plugin Settings
    numbered: false
  info:
    type: info
    label: About
    theme: positive
    text: >
      Configure how the LLMs.txt file is generated for Large Language Models.       
      Open <a href="{{site.url}}/llms.txt" target="_blank">llms.txt</a> or
       <a href="{{site.url}}/sitemap.xml" target="_blank">sitemap.xml</a> to see the output.
    width: 1/2
  description:
    type: textarea
    label: Description
    width: 1/2
  sitemap_enabled:
    type: toggle
    label: Enable Sitemap.xml
    text: 
      - Disabled
      - Enabled
    default: true
    width: 1/4
    help: Enable XML sitemap generation using the same page list as LLMs.txt
  llms_enabled:
    type: toggle
    label: Enable LLMs.txt
    text: 
      - Disabled
      - Enabled
    default: true
    width: 1/4
    help: Enable / Disable plugin output
  llms_cache:
    type: toggle
    label: Enable Caching
    text: 
      - Disabled
      - Enabled
    default: false
    width: 1/4
    help: Enable caching to improve performance
  llms_cacheDuration:
    type: number
    label: Cache Duration (minutes)
    min: 1
    default: 60
    placeholder: 60
    width: 1/4
    when:
      llms_cache: true
  llms_add_trailing_slash:
    type: toggle
    label: Add Trailing Slash 
    text: 
      - Disabled
      - Enabled
    default: true
    width: 1/4
    help: Add "/" at the end of urls.

  excludeTemplatesHeadline:
    type: headline
    label: Exclusion Settings
    numbered: false
    size: h2
  llms_excludeTemplates:
    type: tags
    label: Exclude Templates
    default: error,faq,faqs,faqpage,faq-page
    help: Templates to exclude from the LLMs.txt output

  llms_excludePages:
    label: Exclude Pagzes
    type: multiselect
    help: Pages to exclude from the LLMs.txt output
    max: 100 
    options:
      type: query
      query: site.index.listed

  llms_includePages:
    label: Include Pages
    help: Always include these pages in the LLMs.txt, even if they match exclusion rules.
    type: multiselect
    max: 100 
    options:
      type: query
      query: site.index.listed